### PR TITLE
Added ability to specify localIP

### PR DESCRIPTION
**Pull request by ArmenPoghosyan**
Added an ability to specify the LocalIP manually

### CODE REVIEW

**Comment by luc-github** [comment]
the IP is the IP of the system, it is not up to SSDP to set the IP - I do not understand your PR

**Comment by luc-github** [comment]
@ArmenPoghosyan can you explain your PR ?

**Comment by ArmenPoghosyan** [comment]
> @ArmenPoghosyan can you explain your PR ?
It would be good to have an ability to specify the IP address manually because the protected LocalIP method not always works as expected and gives random IP address when in AP or AP_STA modes
For example see this issue https://github.com/luc-github/ESP32SSDP/issues/38 

Thanks!

**Comment by ArmenPoghosyan** [comment]
> the IP is the IP of the system, it is not up to SSDP to set the IP - I do not understand your PR

Sometimes we don't need the STA IP and instead we need the AP IP because the SSDP may be used to discover devices in the

**Comment by luc-github** [comment]
no that not the same issue

**Comment by luc-github** [comment]
if you cannot get IP you cannot setup the server so I think you misunderstood the API

**Comment by ArmenPoghosyan** [comment]
> if you cannot get IP you cannot setup the server so I think you misunderstood the API

What if we need to set the ethernet IP address?

**Comment by luc-github** [comment]
the eth ip is also available  if set bt DHCP or static: https://github.com/luc-github/ESP32SSDP/blob/master/src/ESP32SSDP.cpp#L164

**Pull request closed without merging**
