### PR TITLE
Header parsings fails rfc7230 OWS specification.

### PR DESCRIPTION
**Pull request by f34rdotcom**
https://greenbytes.de/tech/webdav/rfc7230.html#header.fields
https://greenbytes.de/tech/webdav/rfc7230.html#rule.OWS
SmarThings HUB SSDP sends out its Host header with no white space after ':' causing
the library to fail to parse the message. This patch adds a new state to skip over OWS.

### CODE REVIEW

**Comment by luc-github** [comment]
thank you - I will test it today

**Comment by f34rdotcom** [comment]
Sorry. I was hoping to keep these as different patches to keep it clean :(
Oh well. I have a few more good improvements include ST replies and an efficiency bug. How can I best stage these for your workflow?

**Comment by luc-github** [comment]
ok in that case continue here and let me know when you are done - I will test
no need to make things complex  ^_^

**Comment by luc-github** [comment]
@f34rdotcom could you push your PR to devt branch instead of master ?
I have added travis scripts to help the checking

**Comment by f34rdotcom** [comment]
Shows up using gupnp-universal-cp with a custom schema but still not working under SmartThings. Investigating.

**Comment by f34rdotcom** [comment]
Well I am mostly happy with this but it still has one flaw that will need braining. If multiple systems query the ESP32 with an M-SEARCH each will stack up and delay. I have not a perfect example but this cause the ESP32 to reply to ports that are already closed resulting in ICMP unreachable port XXX errors. One way would be when a packet is to be delayed to place it into some storage container / list and then go back to parsing new UDP messages. Thoughts?

**Comment by luc-github** [comment]
you mean put all packets in kind of buffer waiting to be processed ?
Because how to detected :
>when a packet is to be delayed

**Comment by f34rdotcom** [comment]
Yes but only the necessary parts to send the reply after the _delay. This way the state machine can go back to parsing new packets. Then if a packet with a DELAY of 5 is followed by a packet with a DELAY of 1 the second packet would get replied to in ~1 second. In the current code the second wont be replied to for 6 seconds.

**Comment by f34rdotcom** [comment]
I would keep te queue size small. This happens all the time on a busy network with M-SEARCH happening from multiple hosts but still 5  is plenty IMHO. Just throw an error if it hits a high water mark and make the queue size a config define to adjust for very busy networks.

**Comment by f34rdotcom** [comment]
So far so good. Works ok with GUPnP Universal Control Point and SmartThings HUB. Still sluggish and I loose packets because of ICMP unreachable port but enough packets make it that it is functional. Again I am not using ::schema(). I made my own static schema to test.

**Comment by luc-github** [comment]
ok thank you ^_^

**Comment by f34rdotcom** [comment]
Way to early to submit this here and maybe it should be a different thread but my results are so far very clear. Adding a small queue to hold multiple replies waiting for time to deliver cause all my lag to go away. Now with gupnp-universal-cp and gssdp-discover as well as smartthings now return instantly with a found device. This group of fixes dealt with matching the RFC closer and some fixes. This one I am working on may add more bugs than it fixes in the short term. 

Any chances to test this so far?

Best
 SM

**Comment by luc-github** [comment]
lets do the queue thing in another pr IMHO, I will have time tomorrow to test this PR
so I may merge it quickly

**Comment by f34rdotcom** [comment]
Just going over my code and security and noted that current code allows for sending a fake query with a MX value of 1000 and the ESP32 will stop processing SSDP messages.

**Comment by f34rdotcom** [comment]
@luc-github Here is the queue dev work if for review. 
https://github.com/f34rdotcom/ESP32SSDP/tree/txqueue

Worst I have seen in my house env is 4/5 full.
```
15:14:52.995 -> !DBG: SIZE(1) PID(1) MASK(10000111111110000000000000110) Ready(1) Armed Away(0) Armed Home(0) Bypassed(0)
15:14:52.995 -> [10000001100000003A--],008,[f70600ff1008001c28020000000000]," DISARMED CHIME   Ready to Arm  "
15:14:53.359 -> Update
15:14:53.359 -> SSDP reply queue status: [X----]
15:14:53.359 -> Do not sent
15:14:54.355 -> Update
15:14:54.355 -> *************************RX*************************
15:14:54.355 -> 192.168.1.219:28898
15:14:54.355 -> M-SEARCH * HTTP/1.1
15:14:54.355 -> HOST: 239.255.255.250:1900
15:14:54.442 -> MAN: "ssdp:discover"
15:14:54.442 -> ST: upnp:rootdevice
15:14:54.442 -> MX: 5
15:14:54.442 -> 
15:14:54.442 -> 
15:14:54.442 -> ****************************************************
15:14:54.442 -> *
15:14:54.442 -> 239.255.255.250:1900
15:14:54.442 -> "ssdp:discover"
15:14:54.442 -> MAN: "ssdp:discover"
15:14:54.442 -> upnp:rootdevice
15:14:54.442 -> ST: 'upnp:rootdevice'
15:14:54.442 -> the search type matches all and root
15:14:54.442 -> 5
15:14:54.442 -> Saving deferred SSDP reply to queue slot 1.
15:14:54.442 -> SSDP reply queue status: [XX---]
15:14:54.442 -> Do not sent
15:14:55.349 -> Update
15:14:55.349 -> SSDP reply queue status: [XX---]
15:14:55.432 -> Do not sent
15:14:56.378 -> Update
15:14:56.378 -> Send None
15:14:56.378 -> Sending Response to 192.168.1.204:60315
15:14:56.378 -> *************************TX*************************
15:14:56.378 -> HTTP/1.1 200 OK
15:14:56.378 -> EXT:
15:14:56.378 -> CACHE-CONTROL: max-age=1200
15:14:56.378 -> SERVER: Arduino/1.0 UPNP/1.1 AD2ESP32/2.0
15:14:56.378 -> USN: uuid:38323636-4558-4dda-9188-cda0e60014e4::urn:schemas-upnp-org:device:AlarmDecoder:1
15:14:56.378 -> ST: urn:schemas-upnp-org:device:AlarmDecoder:1
15:14:56.378 -> LOCATION: http://192.168.1.93:80/device_description.xml
15:14:56.471 -> 
15:14:56.471 -> 
15:14:56.471 -> ****************************************************
15:14:56.471 -> SSDP reply queue status: [-X---]
15:14:57.373 -> Update
15:14:57.373 -> SSDP reply queue status: [-X---]
15:14:57.373 -> Do not sent
15:14:58.368 -> Update
15:14:58.368 -> SSDP reply queue status: [-X---]
15:14:58.368 -> Do not sent
15:14:59.363 -> Update
15:14:59.363 -> Send None
15:14:59.363 -> Sending Response to 192.168.1.219:28898
15:14:59.363 -> *************************TX*************************
15:14:59.363 -> HTTP/1.1 200 OK
15:14:59.363 -> EXT:
15:14:59.363 -> CACHE-CONTROL: max-age=1200
15:14:59.458 -> SERVER: Arduino/1.0 UPNP/1.1 AD2ESP32/2.0
15:14:59.458 -> USN: uuid:38323636-4558-4dda-9188-cda0e60014e4::upnp:rootdevice
15:14:59.458 -> ST: upnp:rootdevice
15:14:59.458 -> LOCATION: http://192.168.1.93:80/device_description.xml
15:14:59.458 -> 
15:14:59.458 -> 
15:14:59.458 -> ****************************************************
15:14:59.458 -> SSDP reply queue status: [-----]
15:15:00.357 -> Update
15:15:00.357 -> SSDP reply queue status: [-----]
15:15:00.357 -> Do not sent
15:15:01.352 -> Update
15:15:01.352 -> SSDP reply queue status: [-----]
15:15:01.352 -> Do not sent
15:15:02.347 -> Update
15:15:02.347 -> SSDP reply queue status: [-----]
15:15:02.427 -> Do not sent
15:15:03.010 -> !DBG: SIZE(1) PID(1) MASK(10000111111110000000000000110) Ready(1) Armed Away(0) Armed Home(0) Bypassed(0)
15:15:03.010 -> [10000001100000003A--],008,[f70600ff1008001c28020000000000]," DISARMED CHIME   Ready to Arm  "
15:15:03.375 -> Update
```

**Comment by luc-github** [comment]
wow nice can't wait to test all this today
about 
>fake query with a MX value of 1000 and the ESP32 will stop processing SSDP messages.

only `MX 1000` has issue ?

**Comment by f34rdotcom** [comment]
1000 was just am example. I set the max to time a reply can be delayed to 10000 ms in my txqueue branch(SSDP_MAX_DELAY). MX allows for any value but should be limited to a max of 120 seconds per specifications. If one sends in MX of somebignumber the code will sleep and not read any new packets till the MX expires. The txqueue branch does help this by allowing rx of new packets while ones are in delay pending TX.

**Comment by luc-github** [comment]
Thank you

**Comment by luc-github** [comment]
@f34rdotcom I cannot compile https://github.com/f34rdotcom/ESP32SSDP/tree/txqueue
I think you synced .cpp file but not the .h file ^_^
`error: class 'SSDPClass' does not have any field named '_replySlots'`

**Comment by f34rdotcom** [comment]
Woops ;) thanks.

**Comment by luc-github** [comment]
hmm you have issue with init order :
```
In file included from C:\Users\User\Documents\Arduino\libraries\ESP32SSDP-1.0.1\ESP32SSDP.cpp:30:0:

C:\Users\User\Documents\Arduino\libraries\ESP32SSDP-1.0.1\ESP32SSDP.h: In constructor 'SSDPClass::SSDPClass()':

C:\Users\User\Documents\Arduino\libraries\ESP32SSDP-1.0.1\ESP32SSDP.h:121:19: error: 'SSDPClass::_process_time' will be initialized after [-Werror=reorder]

     unsigned long _process_time;

                   ^

C:\Users\User\Documents\Arduino\libraries\ESP32SSDP-1.0.1\ESP32SSDP.h:113:61: error:   'ssdp_reply_slot_item_t* SSDPClass::_replySlots [5]' [-Werror=reorder]

     ssdp_reply_slot_item_t *_replySlots[SSDP_MAX_REPLY_SLOTS];

                                                             ^

C:\Users\User\Documents\Arduino\libraries\ESP32SSDP-1.0.1\ESP32SSDP.cpp:112:1: error:   when initialized here [-Werror=reorder]

 SSDPClass::SSDPClass() :

 ^

C:\Users\User\Documents\Arduino\libraries\ESP32SSDP-1.0.1\ESP32SSDP.cpp:123:15: warning: list-initializer for non-class type must not be parenthesized

 _notify_time(0)
```

Compilation pass if you init in same order as declaration - be sure you have `-Werror=reorder` flag to verify

**Comment by f34rdotcom** [comment]
Can not seem to get this compiler flag to work. I have an older 1.8.9 Arduino IDE at home. I manually added to my esp32 platform.txt and I see it show up on build but no errors when I mixup the order of the headers :( in any case I "think" i have them right but its late and I am not sure.

**Comment by f34rdotcom** [comment]
Ok office version works better. Let me know how that last commit works.

**Comment by luc-github** [comment]
I tested modifying order yesterday and was ok - 
please push PR - Travis will check automaticaly ^_^
I will again check after

**Comment by f34rdotcom** [comment]
Please confirm this issue is seen using the sample code on the project and I will load and test the same. I saw this behavior on linux using gupnp-universal-cp. It would show the device as soon as the UDP reply was accepted but would later remove if the device xml had errors or incorrect uuid data. I will see if my other half will let me use her laptop with windows 7 today. I did not see gupnp tools for windows but wireshark is how I will be testing.

**Comment by luc-github** [comment]
Yes I use sample code to be sure
using ` _delay = random(0, atoi(buffer)) * 1000L;` instead of ` _delay = random(0, atoi(buffer) * 1000L);`

Does not prevent the icon to disapear but allow it to come back if doing refresh

also reverting to master, the icon does not disapear at all, tested both several times during couple of hours each, I tested master, Devt and with schema-rewrite branch

**Comment by f34rdotcom** [comment]
Testing and so far its not showing any issues on Win8.1 and no errors on gupnp-universal-cp. I can test with Windows 10 and 7 at my office on Monday. I will keep testing.

**Comment by f34rdotcom** [comment]
I can confirm that devices including my AD2* device using this code does disappear some long duration maybe an hour after discovery in explorer window on Windows 8. Other devices and at some point all devices seem to disappear so that is not a lot of help. While digging over specs and checking packets I noted some were still delayed too long. I am not sure it will help but its more accurate. 9e36c19b19a96389290312bcb66e476d3588a2f2 I have seen no difference in this patch in the issue of disappearing.

**Comment by f34rdotcom** [comment]
Headed out for a few hours with windows and linux tests so far both are still showing my device as alive. The only change was that delay patch.

**Comment by f34rdotcom** [comment]
ok back. Seems ok still. Odd before I left all devices but mine were gone back and they are all back.

**Comment by luc-github** [comment]
Hi thank you for checking - On my side I can also confirm with original code (master branch) no icon dispear after all night running, (I just wake up ^_^)

I will check yoru patch and report

**Comment by luc-github** [comment]
ok here what I have noticed :
with original code (master branch) : 
- No need refresh network window after flash or connection to make icon appear
- closing or let open for hour(s) the network window : the esp32 icon is still there
- other devices icons disapear after a while need a refresh to make them back
image


with new patch (your branch):
- need refresh network window after flash or connection to make icon appear
- after some time (less than one hour) the icon disapear, need a refresh to bring it back
- other devices  icons disapear after a while need a refresh to make them back
image

**Comment by luc-github** [comment]
Ok I spent all day testing and comparing with master
I have isolate 3 points :
right is your fork including latest patch, left is my modified version to revert to original code
image
image

changes lines 216 and 496 make the icon to apear when esp start in Network windows without need of refreshing it

change line 214 keep the icon live

I did not dig in RFC to be honest just read code and check what would make sense

1  - line 216 - to apear in network windows type must be `upnp:rootdevice` if not it was not displayed in original code, so may be for this type (upnp:rootdevice) all answers must be upnp:rootdevice instead of requested type 

2 - line 496 : logic/typo error ? as the pending variable is not used

3 - line 214 : is formating correct ? if format is incorrect the answer could be ignored as you mentioned earlier

this is experimental conclusion as I am not expert in upnp ^_^ I could definitly be wrong
 but result is what we expect with these changes reverted

What do you think?

**Comment by f34rdotcom** [comment]
Morning. I was up late coding so it will be a slow start today and may not get back to this till later tonight. I agree and recall when reviewing specs that this nuance in reply with root or actual device is critical. I believe it is very close but yes maybe is missing something. One thing I noted when I did the patch and should have added a FIXME is that if asked for ssdp:all we need to return two or more packets. One for root and one for the child and more if multiple children if the lib supported it.

I wonder if the "NOTIFY" message is not working or is not formatted correctly. So far I see the same results on Windows 8 many but not all of my devices show up.

On my home network my Windows 8 system shows a few of my devices but after a few hours or some random time they all start to disappear until they are all gone. Wish I had a "known good" device on my network so I could compare.

The line 496 is not the same as what I have?
https://github.com/f34rdotcom/ESP32SSDP/blob/9e36c19b19a96389290312bcb66e476d3588a2f2/ESP32SSDP.cpp#L496

**Comment by luc-github** [comment]
@f34rdotcom, no problem ^_^ night time now here 

about line 496
your flush is based on `sent`
the working flush is based on ` _pending` so behavior may slightly differ with current code

**Comment by luc-github** [comment]
@f34rdotcom I am no digging more and I see something else:
```

**Comment by f34rdotcom** [comment]
I think that is good. It should respond back with rootdevice is the query was rootdevice and if the query is all it should respond back with rootdevice.

I do see the bug. Spotted it a few hours ago. The Notify is bad. It uses the saved _responseType but should use "rootdevice". I may be up to fix tonight but its late and im about cooked. And I am busy tomorrow afternoon. Maybe in the AM. SHould be an easy fix. Before sending notify restore set _resposneType to "rootdevice".

**Comment by luc-github** [comment]
I found another glitch :
_respondType is not initialized when starting:

I got:
```
Starting SSDP...
Ready!
Sending Notify to 239.255.255.250:1900
*************************TX*************************
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
NTS: ssdp:alive
CACHE-CONTROL: max-age=1200
SERVER: Arduino/1.0 UPNP/1.1 Philips hue bridge 2012/929000226503
USN: uuid:38323636-4558-4dda-9188-cda0e600bc73
NT: 
LOCATION: http://192.168.1.46:80/description.xml
```

when should be
```
Starting SSDP...
Ready!
Sending Notify to 239.255.255.250:1900
*************************TX*************************
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
NTS: ssdp:alive
CACHE-CONTROL: max-age=1200
SERVER: Arduino/1.0 UPNP/1.1 Philips hue bridge 2012/929000226503
USN: uuid:38323636-4558-4dda-9188-cda0e600bc73
NT: upnp:rootdevice
LOCATION: http://192.168.1.46:80/description.xml
```
or what ever the device is

**Comment by luc-github** [comment]
>I think that is good. It should respond back with rootdevice is the query was rootdevice and if the query is all it should respond back with rootdevice.

Hmm  if devicetype is `urn:schemas-upnp-org:device:Basic:1` and not `upnp:rootdevice` it should not respond `NT: upnp:rootdevice`

**Comment by f34rdotcom** [comment]
`Yep same bug ish :) The same fix I mentioned should fix this too.

**Comment by f34rdotcom** [comment]
One thing I mentioned is that if "ssdp:all" is the query we actually need to reuturn 1+N packets where we return "rootdevice" and N number of children. In this case just one. so we need to actually return two packets. That is now possible with the delay queue  but I was hoping just returning rootdevice would be sufficient.

**Comment by f34rdotcom** [comment]
Ok testing now.
https://github.com/f34rdotcom/ESP32SSDP/commit/7348fc75ac19741d2d1c39388e0f80416b139ec1

**Comment by luc-github** [comment]
@f34rdotcom testing on my side too - seems now the icon show at start as expected 
now let the pc on to see if icon stay or disapear after a while and if need a refresh

**Comment by f34rdotcom** [comment]
Same here. All other devices disappeared so far from the window but my AlarmDecoder is still UP after 1.5hrs 
I am out for the day back tonight.
Best
 SM

**Comment by f34rdotcom** [comment]
Whooot! Still going solid.

**Comment by luc-github** [comment]
Same here after after one night - I think it is  good now^_^

**Comment by f34rdotcom** [comment]
I would like to change this. Its too noisy and IMHO not very helpful during debug.
https://github.com/f34rdotcom/ESP32SSDP/blob/7348fc75ac19741d2d1c39388e0f80416b139ec1/ESP32SSDP.cpp#L306

**Comment by luc-github** [comment]
no problem

**Comment by f34rdotcom** [comment]
Every time I update I have to change this line to my own before I commit. Will be nice when can be done externally via api call.
  sprintf(_uuid, "38323636-4558-4dda-9188-cda0e6%02x%02x%02x",

Ok I can submit a pull request from the reply-delay-fix-1 branch just say when :)
I just pushed the debug printf change.

**Comment by luc-github** [comment]
>Every time I update I have to change this line to my own before I commit. Will be nice when can be done externally via api call.
sprintf(_uuid, "38323636-4558-4dda-9188-cda0e6%02x%02x%02x",

yes https://github.com/luc-github/ESP32SSDP/issues/5 should be done tomorrow

I did not wanted to push code until the issues were closed, you can push PR - I will then rebase my rewrite branch and push the change to it then push it to devt

**Pull request merged**
